include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - packages/flutter_inappwebview_android/**

linter:
  rules:
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_final_locals: true
